import type { Product } from "@/types/domain";

/**
 * Development seed. Mirrors the products shown in the design mockups so the UI
 * has realistic content before Supabase is connected. Prices in centavos.
 */
export const SEED_PRODUCTS: Product[] = [
  {
    id: "p-ser-0045",
    sku: "SER-0045",
    barcode: "7891000100045",
    name: "Serum Facial Iluminador",
    description: "Aurélia Radiance Elixir 30ml",
    category: "cosmeticos",
    costCents: 9000,
    priceCents: 18900,
    unit: "un",
    stock: 42,
    lowStockThreshold: 10,
    color: null,
    size: null,
    imageUrl: null,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-dif-8821",
    sku: "DIF-8821",
    barcode: "7891000188218",
    name: "Difusor Cerâmica Terracota",
    description: "Difusor artesanal com bandeja de madeira",
    category: "aromaterapia",
    costCents: 12000,
    priceCents: 24590,
    unit: "un",
    stock: 5,
    lowStockThreshold: 8,
    color: null,
    size: null,
    imageUrl: null,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-vel-0012",
    sku: "VEL-0012",
    barcode: "7891000100128",
    name: "Vela Artesanal Lavanda",
    description: "Vela de soja perfumada, 200g",
    category: "aromaterapia",
    costCents: 3500,
    priceCents: 7500,
    unit: "un",
    stock: 124,
    lowStockThreshold: 20,
    color: null,
    size: null,
    imageUrl: null,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-acc-4402",
    sku: "ACC-4402",
    barcode: "7891000144022",
    name: "Bracelete Minimalist Gold",
    description: "Bracelete banhado a ouro 18k",
    category: "acessorios",
    costCents: 21000,
    priceCents: 42000,
    unit: "un",
    stock: 2,
    lowStockThreshold: 5,
    color: null,
    size: null,
    imageUrl: null,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-towl-909",
    sku: "TOWL-909",
    barcode: "7891000909096",
    name: "Toalha Spa Premium",
    description: "Toalha de algodão egípcio",
    category: "acessorios",
    costCents: 5500,
    priceCents: 11500,
    unit: "un",
    stock: 28,
    lowStockThreshold: 10,
    color: null,
    size: null,
    imageUrl: null,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p-soap-122",
    sku: "SOAP-122",
    barcode: "7891000122129",
    name: "Sabonetes Orgânicos Kit",
    description: "Kit com 6 sabonetes artesanais",
    category: "cosmeticos",
    costCents: 2800,
    priceCents: 5800,
    unit: "kit",
    stock: 56,
    lowStockThreshold: 15,
    color: null,
    size: null,
    imageUrl: null,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
